version: '3'
services:
  api:
    image: 'node:16.13.0-alpine'
    container_name: api_container
    ports:
      - "3030:3030"
    volumes:
      - ./:/api
    working_dir: /api
    command: [sh, -c, npm install && npm run dev && tail -f /dev/null]

  web:
    image: 'nginx:1.17.10-alpine'
    container_name: web_container
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./conf/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/index.html:/var/www/index.html