version: '3'
services:
  api:
    image: 'node:16.13.0-alpine'
    container_name: api_container
    ports:
      - "3030:3030"
    volumes:
      - ./:/api
    working_dir: /api
    command: [sh, -c, npm install && npm run dev && tail -f /dev/null]